# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pru < Formula
  desc "pru is a tool that updates pull requests branch from the base branch that contains specified files."
  homepage "https://github.com/winebarrel/pru"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/pru/releases/download/v0.3.0/pru_0.3.0_darwin_amd64.tar.gz"
      sha256 "b441474431503581e2fd2c6db92bac161685f635393ecfc75866aa51c651820d"

      def install
        bin.install 'pru'
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/winebarrel/pru/releases/download/v0.3.0/pru_0.3.0_darwin_arm64.tar.gz"
      sha256 "40e218726fafcd4de85ae4f8c5e63c00dd5b664b2600b385d2c1084b6648d380"

      def install
        bin.install 'pru'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/pru/releases/download/v0.3.0/pru_0.3.0_linux_amd64.tar.gz"
      sha256 "11a39145897fb3478526ba99cf3a650d99b6513ded426a8e57aba9ee33ef2647"

      def install
        bin.install 'pru'
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/winebarrel/pru/releases/download/v0.3.0/pru_0.3.0_linux_arm64.tar.gz"
      sha256 "f2a2f55472072af36de05c0c10de087fbe26bc7aaf73ff1ca13d19a3abc3c10a"

      def install
        bin.install 'pru'
      end
    end
  end
end
