# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pru < Formula
  desc "pru is a CLI that updates the pull request branch from the base branch that contains the specified file."
  homepage "https://github.com/winebarrel/pru"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/pru/releases/download/v0.1.1/pru_0.1.1_darwin_amd64.tar.gz"
      sha256 "7eb7b08197b69a2dbab7861882d588bdb0953fd00f59691e451e887f617d2f69"

      def install
        bin.install 'pru'
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/winebarrel/pru/releases/download/v0.1.1/pru_0.1.1_darwin_arm64.tar.gz"
      sha256 "3281cdf565fd477e39ff7c93e50af1a6ca18456b0451c8ed815b9717c49d8ebb"

      def install
        bin.install 'pru'
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/winebarrel/pru/releases/download/v0.1.1/pru_0.1.1_linux_arm64.tar.gz"
      sha256 "15e3efbc3f0f0c969ec95db9d5fba3c3b832519baf93bd7e5c81d9982c627888"

      def install
        bin.install 'pru'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/pru/releases/download/v0.1.1/pru_0.1.1_linux_amd64.tar.gz"
      sha256 "3a525110f9ae33b1b8a55cc3b01680ae7d9a6d65a8237f3014b9f4581ceb2f36"

      def install
        bin.install 'pru'
      end
    end
  end
end
